/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthStaffIndexImport } from './routes/_auth/staff/index'
import { Route as AuthDashboardIndexImport } from './routes/_auth/dashboard/index'
import { Route as AuthStaffIdIndexImport } from './routes/_auth/staff_/$id/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthStaffIndexRoute = AuthStaffIndexImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthDashboardIndexRoute = AuthDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthStaffIdIndexRoute = AuthStaffIdIndexImport.update({
  id: '/staff_/$id/',
  path: '/staff/$id/',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/staff/': {
      id: '/_auth/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthStaffIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/staff_/$id/': {
      id: '/_auth/staff_/$id/'
      path: '/staff/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthStaffIdIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthStaffIndexRoute: typeof AuthStaffIndexRoute
  AuthStaffIdIndexRoute: typeof AuthStaffIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthStaffIndexRoute: AuthStaffIndexRoute,
  AuthStaffIdIndexRoute: AuthStaffIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/staff': typeof AuthStaffIndexRoute
  '/staff/$id': typeof AuthStaffIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/staff': typeof AuthStaffIndexRoute
  '/staff/$id': typeof AuthStaffIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/staff/': typeof AuthStaffIndexRoute
  '/_auth/staff_/$id/': typeof AuthStaffIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/dashboard' | '/staff' | '/staff/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/dashboard' | '/staff' | '/staff/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login/'
    | '/_auth/dashboard/'
    | '/_auth/staff/'
    | '/_auth/staff_/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/dashboard/",
        "/_auth/staff/",
        "/_auth/staff_/$id/"
      ]
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_auth/dashboard/": {
      "filePath": "_auth/dashboard/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/staff/": {
      "filePath": "_auth/staff/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/staff_/$id/": {
      "filePath": "_auth/staff_/$id/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
